import type { Metadata } from "next";
import "./globals.css";
import { Inter, Space_Grotesk } from "next/font/google";
import Sidebar from "@/components/sidebar";

const inter = Inter({
  subsets: ["latin"],
});

const space = Space_Grotesk({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} `}>
      <body className="min-h-full flex flex-col bg-gray-900 ">{children}</body>
    </html>
  );
}
